name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: base.tex
          working-directory: vivado1/
          latexmk_use_lualatex: true
          latexmk_shell_escape: true
          
      - name: Upload PDF file
        uses: actions/upload-artifact@v1
        with:
          name: PDF
          path: main.pdf
