name: Build and deploy latex sources to GitHub Pages
on: push
jobs:
  build:
    # Базовая ОС, на которой будут исполняться команды. Оставим ubuntu
    runs-on: ubuntu-latest
    steps:
    # Необходимо использовать этот action, чтобы получить содержимое репо
    - uses: actions/checkout@v2
    - name: Install шрифты
      run: sudo apt-get install ttf-mscorefonts-installer
    # Компилируем документ
    - name: Build document
      uses: xu-cheng/latex-action@v2
      with:
        # Переименуйте, если у вас другой файл
        root_file: base.tex
        # Больше параметров в офф. документации
        working_directory: vivado1/
        # Аргументы, к которыми запускать компилятор (latexmk)
        work_in_root_file_dir: true
        extra_fonts: |
         fonts/*.ttf
        # -jobname=<name> дает возможность поменять имя выходного файла
        args: -jobname=my_doc -pdf -file-line-error -halt-on-error -interaction=nonstopmode
        compiler: latexmk
        latexmk_use_lualatex: true
        latexmk_shell_escape: true
