name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
    with:
        # Переименуйте, если у вас другой файл
        root_file: main.tex
        # Больше параметров в офф. документации
        working_directory: vivado1/
        # Аргументы, к которыми запускать компилятор (latexmk)
        # -jobname=<name> дает возможность поменять имя выходного файла
        args: -jobname=my_doc -pdf -file-line-error -halt-on-error -interaction=nonstopmode
        compiler: latexmk
         
     
