name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
 	- name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

	- name: Install dependencies
      	run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt	
	 - name: Make output folder
      	run: mkdir output
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
	working_directory: ./vivado1
          root_file: base.tex
	
          latexmk_use_lualatex: true
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: main.pdf
